### ISSUE TITLE
OpenLayers drag seems broken.

### ISSUE THREAD

**Issue by cpaulik** [pmlrsg/GISportal#37]
Hi, Thanks for the new release. It is great and I was very happy to see that the plotting functionality is now also based on Python.

But there is one thing that only became an issue recently. It seems that in the latest dockerfile as well as on the master branch the dragging of the map is broken. The map is dragged further than the mouse moves. Also trying to draw a polygon for plotting gets stuck in dragging the map around. 

This still worked middle of last week.

**Comment by bcalton** [comment]
Can you let me know what browser you are using, please?

**Comment by cpaulik** [comment]
Yeah, I tried on

- Firefox 44.0.2
- Chrome  48.0.2564.116

both on Ubuntu 14.04

**Comment by bcalton** [comment]
@cpaulik  - this commit https://github.com/pmlrsg/GISportal/commit/d004d38fd0f059b9d3c824f373d56abbe673f024 solves the issue. It's merged into the master branch, but as yet it's not in the Docker Hub container.

**Comment by cpaulik** [comment]
Thanks. Just to clarify, this has solved the problem with drawing the polygon but not the strange dragging behavior of the map.
