### ISSUE TITLE
Any way to update the layer cache?

### ISSUE THREAD

**Issue by cpaulik** [pmlrsg/GISportal#41]
I have a thredds WMS Service that gets extended every day with new data. In the past there was a way to update the layer cache. Is seems these scripts were removed in  76a882b64471a12128a278006cc8f9a9fffa3776 

Is there any way to do that now? 

I've tried some of the calls in GISportal/app/lib/site_settings.js but was not successful.

**Comment by ojsdude** [comment]
If you have admin rights you should be able to click the 'Configure Internal Layers' button under the 'Display Settings' tab. This will allow you to refresh any layers by clicking update

**Comment by cpaulik** [comment]
Does this mean I will have to configure the user dashboard? I would really need something that I can automate since this would be necessary every day.

**Comment by cpaulik** [comment]
So it seems that a call to `/app/settings/load_new_wms_layer?url=...&refresh=true` refreshes the json files in the `layers` directory. That still leaves wrong `FirstDate` and `LastDate` information in the default layers but I guess that is not really avoidable.

**Comment by cpaulik** [comment]
Is there any reason why the `FirstDate` and `LastDate` information is not loaded from the json file in the layers directory when the layer is added to the map?

**Comment by ojsdude** [comment]
Currently that is the case, We are hoping to release a web API eventually. In the mean time, if you can find a way to run the 'load_new_wms_layer' function using the url of the layers on the server. This is what is used by the refresh call. The problem with that will be that you need to have oauth to run this function. We will look soon at adding automation with the ability to define an interval in the front end. do you have any thoughts on that?

**Comment by ojsdude** [comment]
Could you explain a little more about what is happening with the first and last date when the layer is reloaded? are you saying that they are updated in the layers directory but not in the user specific (or global) json file?

**Comment by cpaulik** [comment]
What do you mean with needing to have oauth? In my tests on our installation I could just call `load_new_wms_layers` without any authentification. 

I have not yet looked at the front end really since there are some problems with loading the dashboard because of our proxy setup. If the admin can specify a refresh interval or maybe even a cron expression like thredds uses then that would be great.

**Comment by cpaulik** [comment]
> Could you explain a little more about what is happening with the first and last date when the layer is reloaded? are you saying that they are updated in the layers directory but not in the user specific (or global) json file?

In my case there are three files in play. 

1. There is the json file in `site_settings/subfolder/temporary_cache` which is updated. 
2. Then there is the file in `site_settings/subfolder` which is loaded by default when the GISportal is started which is not updated and probably should not be updated since it can contain manually added metadata information. But maybe I'm doing that wrong? 
3. The files in the `site_settings/layers` directory also get updated.

So the issue is file number 2 in my case since it contains metadata that the THREDDS Server does not have and it is used for loading the date range.

**Comment by ojsdude** [comment]
You're right, that's my mistake. `load_new_wms_layers` is available at any user level.

And that's okay then. The admin interface that we have created is there for a range of users and abilities so allowing them to input cron syntax is maybe not the best and tick boxes would be ample, if a user wanted to run a cron they could create it on the server themselves

**Comment by ojsdude** [comment]
When loading and refreshing from the front end, all of the files should be updated and there is a function called `gisportal.editLayersForm.refreshOldData` that you may be able to look at for reference. This refreshes the data, making sure to keep values that have been edited by the user

**Comment by cpaulik** [comment]
If `load_new_wms_layers` is OK to use then I can include a call to that in my data update script. That's fine then. 

Looking at `gisportal.editLayersForm.refreshOldData` it seems very hard to call that from a script that does this daily especially because `/app/settings/update_layer` seem to require authentication. So I think I'll probably have to write something custom as an interim solution.

Thanks for you help.

**Comment by bcalton** [comment]
@cpaulik This afternoon we have released a new version of code that includes an API. You can use this API to update the server caches which you may find useful given the conversation on this ticket.

The details of how to use it are on the wiki at https://github.com/pmlrsg/GISportal/wiki/API-Usage

**Comment by cpaulik** [comment]
@bcalton Thanks a lot. This is perfect timing since the automatic updating of our GISportal instance will be implemented in the coming weeks.
