### ISSUE TITLE
Impossible to use `_` in path name?

### ISSUE THREAD

**Issue by cpaulik** [pmlrsg/GISportal#42]
It seems that `/` in domains are replaced by `_` without taking care of existing `_` characters. If this is by design then it should be at least documented somewhere.

**Comment by auspex** [comment]
Strictly speaking, neither '/' or '_' are supposed to be in domain names, but '/' is simply impossible! 

I'm guess you are seeing this in the prompt in the install where it asks `Enter the domain name (and path, without the http:// part), e.g. 'www.example.com/portal'`, and it's actually the _path_ that's a problem.

And, so, while `www.example.com/portal` would map to `www.example.com_portal`, `www.example.com/portal/path` and `www.example.com/portal_path` would both map to `www.example.com_portal_path`.  

It seems to me that that's only a problem if somewhere the software reverses the transposition and changes what should have been underscores (perfectly permissible in paths) to `/`. But if that happens, it's definitely a bug.

**Comment by cpaulik** [comment]
I'll recheck but I as far as I remember it was a bug since the `_` in the path was not properly handled.

**Comment by cpaulik** [comment]
Just checked and this was fixed or never an issue.
