### ISSUE TITLE
Share button not working / throws error javascript error

### ISSUE THREAD

**Issue by cpaulik** [pmlrsg/GISportal#46]
First of all thanks for all the help on the other issues.

This might be more of a question than an issue.

The `src/js/openid.js` file is not in the `coreFiles` in the Gruntfile so the `gisportal.openid` object is not created. But even after adding it the Share button does not produce an URL. I saw some todos about this in the code so is this even supposed to work in the current state?

**Comment by ojsdude** [comment]
Hi @cpaulik,

OpenID is the old authentication that was used and is now defunct. The Share button at the moment is a knows issue and will be fixed over the next week or so. I will let you know when the issue has been fixed

Thanks,

OJ

**Comment by ojsdude** [comment]
4676d0da659c934dd02e67fe4ca5df1be464bc64 has added this feature. Master and Dev both now have the up to date version
