### ISSUE TITLE
Sharing a map does not reproduce the set colorbar min and max value

### ISSUE THREAD

**Issue by cpaulik** [pmlrsg/GISportal#48]
I've just tried this on the running portal at `https://wci.earth2observe.eu/portal` so sorry if it was already fixed in a development version. 

Anyway. When looking at the map accessible under the link https://wci.earth2observe.eu/portal/?state=a0ce77 you can see that the soil moisture has black areas because it is automatically scaled between `0.05...` and `0.433..`. In the original map that I created before pressing the share button I manually scaled the data between 0 and 0.6 so that it looks nice. It would be great if the colorbar settings could be also stored in the shared map state.

**Comment by NickMackz** [comment]
Hi @cpaulik 

This has been fixed now and merged into master with 5d0977b9d41eb6162fb21ee53bc1e6a66ab44fe3
